#!/bin/bash

# cache the *original working directory if not already defined
[[ -z ${OWD} ]] && { OWD="$(cd "$(dirname "${0}")" && pwd -P)"; }

# Load OS variables to figure out what we're running on.
source /etc/os-release

PLATFORM="${ID} ${VERSION_ID}"
# If this is Ubuntu 16.04 through Ubuntu 18.10.x, Debian 8 or 9, or CentOS 7...
[[ ${PLATFORM} =~ ^(ubuntu 1[6-8]\.(04|10)[.0-9]*|debian [89]|centos 7)$ ]] && {
    SERVICE_CONTROL_CMD='$(sudo systemctl ${ACTION} ${SERVICE_ID}.service)'
    SERVICE_DISABLE_CMD='$(sudo systemctl disable ${SERVICE_ID}.service)'
    SERVICE_ENABLE_CMD='$(sudo systemctl enable ${SERVICE_ID}.service)'
    SERVICE_STATUS_CMD='$(sudo systemctl is-active ${SERVICE_ID}.service)'
    SERVICE_INACTIVE_TEST="inactive"
} || {
    SERVICE_CONTROL_CMD='$(sudo service ${SERVICE_ID} ${ACTION})'
    SERVICE_DISABLE_CMD='$(sudo chkconfig ${SERVICE_ID} off)'
    SERVICE_ENABLE_CMD='$(sudo chkconfig ${SERVICE_ID} on)'
    SERVICE_STATUS_CMD='$(ps -ef | grep -v grep | grep ${SERVICE_ID} | wc -l)'
    SERVICE_INACTIVE_TEST="0"
}

timestamp() {
    case ${1} in
        "-n")
            date +%Y%m%d%H%M%S%N;
            ;;

        "-m")
            date +%Y%m%d%H%M%S%N | cut -b1-17;
            ;;

        *)
            date +%Y%m%d%H%M%S;
            ;;
    esac
}

# Provides a translation to use init.d or sysv service controls as appropriate for OS version.
# Call is in the form of manageService <service> <action>
# Note that this function uses sudo so there's no need to sudo the call itself.
manageService() {
    SERVICE_ID="${1}"
    ACTION="${2}"
    $(eval echo ${SERVICE_CONTROL_CMD}) || die "Attempted to ${ACTION} the service ${SERVICE_ID}, but failed"
}

# Indicates whether the service is active or inactive. Can be used in if statement with the form:
# if $(isServiceActive <service>); then echo Hi there.; fi
isServiceActive() {
    SERVICE_ID="${1}"
    [[ "$(eval echo ${SERVICE_STATUS_CMD})" != ${SERVICE_INACTIVE_TEST} ]] && { true; } || { false; }
}

# Enables or disables the service. Should be in the form of:
# toggleService <service> [on|off]
toggleService() {
    SERVICE_ID="${1}"
    ACTION="${2}"
    [[ ${ACTION} == "off" ]] && { $(eval echo ${SERVICE_DISABLE_CMD}); } || { $(eval echo ${SERVICE_ENDABLE_CMD}); }
}

# Exit with error status
die() {
    echo >&2 "${@}"
    exit -1
}

# setFolderOwner uses the first argument for the owner and group name. All other arguments are presumed to be folders.
# This runs two separate chown operations, the first traverses through symlinks, the second affects the actual symlink.
# This means that any folder hierarchy will be changed, including all linked folders.
setFolderOwner() {
    OWNER=${1}
    shift

    echo Setting ${OWNER} as owner of the following folder\(s\) and contents: ${@}

    sudo chown -RfL ${OWNER}:${OWNER} ${@}
    sudo chown -Rfh ${OWNER}:${OWNER} ${@}
}

startTomcat() {
    if $(isServiceActive ${TOMCAT}); then
        echo Tomcat is running, restarting.
        manageService ${TOMCAT} stop
        sudo rm -rf /var/log/${TOMCAT}/*
        manageService ${TOMCAT} start
    else
        echo Tomcat is not running, starting.
        sudo rm -rf /var/log/${TOMCAT}/*
        manageService ${TOMCAT} start
    fi
}

stopTomcat() {
    if $(isServiceActive ${TOMCAT}); then
        echo Tomcat is running, stopping it now.
        manageService ${TOMCAT} stop
    else
        echo Tomcat is not running, nothing to do.
    fi
}

monitorTomcatLog() {
    INDEX=0
    until [[ -e /var/log/${TOMCAT}/catalina.out || ${INDEX} > 5 ]]; do
        ((INDEX += 1))
        sleep 2
    done
    [[ -e /var/log/${TOMCAT}/catalina.out ]] && { return 0; } || { return 127; }
}

monitorTomcatStatus() {
    STATUS_MSG="Server startup in"
    QUIET="--quiet"
    WAIT_FOR=180
    while [[ $1 ]]; do
        if [[ $1 =~ ^[0-9]+$ ]]; then
            WAIT_FOR=$1
        elif [[ $1 == "verbose" ]]; then
            QUIET=""
        else
            STATUS_MSG=$1
        fi
        shift
    done
    echo ""
    # First check if it's already completed start-up. This happens when the web app isn't loaded on VM creation, e.g. xnat-dev.
    if [[ (($(STATUS_MSG="Server startup in"; grep "${STATUS_MSG}" /var/log/${TOMCAT}/catalina.out | wc -l) == 0)) ]]; then
        timeout ${WAIT_FOR} sed ${QUIET} "/${STATUS_MSG}/ q" <(timeout $((WAIT_FOR + 5)) tail -n 0 -f /var/log/${TOMCAT}/catalina.out)
        STATUS=$?
        if [[ ${STATUS} == 0 ]]; then
            TOKEN=$(grep "${STATUS_MSG}" /var/log/${TOMCAT}/catalina.out | sed 's/^.*\('"${STATUS_MSG}"'.*$\)/\1/')
            echo Found requested token in Tomcat startup log: "${TOKEN}";
        else
            echo Did not find requested token in Tomcat startup log: "${STATUS_MSG}".
            echo The last lines in the log are:; tail -n 40 /var/log/${TOMCAT}/catalina.out;
        fi
        return ${STATUS}
    else
        echo It looks like Tomcat started before I started monitoring.
        echo Maybe XNAT\'s not installed yet?
        echo Status message was: $(grep "${STATUS_MSG}" /var/log/${TOMCAT}/catalina.out).
        return -1
    fi
}

monitorTomcatStartup() {
    monitorTomcatLog $@
    STATUS=$?
    [[ ${STATUS} == 0 ]] || { echo No start-up log for Tomcat found at /var/log/${TOMCAT}. Status unknown, exiting without monitoring start-up progress.; return ${STATUS}; }
    monitorTomcatStatus $@
    return $?
}

