package org.nrg.xnat.daos;

import java.util.List;

import org.nrg.framework.orm.hibernate.AbstractHibernateDAO;
import org.nrg.xnat.entities.CsvTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class CsvTemplateDAO extends AbstractHibernateDAO<CsvTemplate> {

	/**
	 * Dao method that retrieves all CSV Templates generated by this XNAT
	 * deployment.
	 *
	 * @return A list containing all of CSV Templates generated by this XNAT
	 *         deployment.
	 */
	public List<CsvTemplate> findAllTemplates() {
		return findAll();
	}

	/**
	 * Dao method that retrieves the CSV Template of the given Template Id.
	 * 
	 * @param id CsvTemplate Id.
	 * 
	 * @return {@link CsvTemplate CsvTemplate} of the given id.
	 */
	public CsvTemplate findTemplateById(final long id) {
		return retrieve(id);
	}
	
	/**
	 * Dao method that retrieves the CSV Template of the given Template Id.
	 * 
	 * @param id CsvTemplate Id.
	 * 
	 * @return {@link CsvTemplate CsvTemplate} of the given id.
	 */
	public List<CsvTemplate> findTemplatesByProjectId(final long projectId) {
		return findByProperty("project", projectId);
	}

}
